reactjs/react-autocomplete

examples/async-data/app.js, examples/custom-menu/app.js, examples/static-data/app.js, lib/Autocomplete.js, lib/__tests__/Autocomplete-test.js
a.k.a. replace `props.initialValue` with `props.value`. This change makes the
behaviour of Autocomplete closer to that of native input elements, i.e. you are
forced to always supply the current value which the input should display, and
the element will provide the updated value via the `onChange` callback (and
`onSelect`).
Upgrade path:
Before:
```js
class MyWidget extends Component {
render() {
return (
<Autocomplete
initialValue="hello"
/>
)
}
}
```
After:
```js
class MyWidget extends Component {
constructor() {
this.state = { value: 'hello' }
}
render() {
return (
<Autocomplete
value={this.state.value}
onChange={event => this.setState({ value: event.target.value })}
onSelect={value => this.setState({ value })}
/>
)
}
}
```
This is obviously a breaking change.
Closes #49
=> Stop keeping value in state

examples/async-data/app.js, examples/custom-menu/app.js, examples/static-data/app.js, lib/Autocomplete.js, package.json
Lodash is massive and quite unnecessary for generating something as simple as a unique ID. The minified build of react-autocomplete is 72kb (!!!!!!). Besides, consumers should be able (and I'd argue responsible) for supplying an ID.
The alternative to an ID was putting the input inside the label, but I figured that wouldn't be desirable given that it could possibly break some layouts.
=> [removed] Remove lodash dependency and hardcoded label

package.json
1. Demote React to a peer dependency. Having React as a direct dependency can cause multiple versions of React to be bundled in applications that depend on a React version that doesn't match `^0.14.7`.
2. Allow both 0.14 and 15 versions of React
3. Remove duplicate babel-preset-es2015 dependency
=> Dependency cleanup

lib/Autocomplete.js
This is to prevent autocomplete from happening when clicking a disabled input
field.
The `ownerDocument` check is paranoid since I couldn't find any documentation
as to when support was added to WebKit/Blink. It's in the DOM level 2 spec, so
support should be widespread.
The alternative to this fix is to explicitly check `input.disabled`.
http://quirksmode.org/dom/core/#t136
https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument
=> [fixed] Prevent autocomplete when clicking a non-focusable input

lib/Autocomplete.js, lib/__tests__/Autocomplete-test.js
While trying to debug #80 I discovered that clicking the input field to
"confirm" a suggestion didn't work as expected.
The problem:
1. Navigate to https://reactcommunity.org/react-autocomplete/static-data/
2. Type 'a' in input field
3. Observe that the input has been filled with 'Alabama'
4. Click anywhere inside the input field
5. Observe that the highlighted selection is gone, and the menu has been closed
6. Click/tab outside the input
7. Observe that the input value has been reverted to 'a'
This change ensures that clicking in the input field has the same effect as
clicking the highlighted item in the suggestion menu.
=> [fixed] Select highlighted item on input click

lib/Autocomplete.js, lib/__tests__/Autocomplete-test.js
The default behaviour of hitting `Return` in a `<input type=text>` is to submit
the immediate surrounding form. I would hazard a guess that this isn't the
expected result when using `Return` to select an item in the autocomplete
menu. Since we don't expose the event object to the consumer via `onSelect` we
need to make sure we're making the most sensible choice by default.
Hitting `Return` a second time (after the menu has closed itself) will
result in the default, expected behaviour.
=> [changed] Prevent `Return` in menu from submitting surrounding form

lib/Autocomplete.js
You can do this via `inputProps`, but since the whole point of this component
is to provide a custom autocomplete solution it makes sense to disable the
native counterpart. If this proves to be problematic we can change the ordering
so that the consumer can override it via `inputProps: { autoComplete: 'on' }`.
=> [changed] Disable native autocomplete

lib/Autocomplete.js
fixes #39 `Uncaught TypeError: Cannot read property 'ownerDocument' of undefined`
=> fix arrow up/down bug when list is empty

package.json
`npm start` finally works when using npm 3.
=> Update rackt-cli (fixes #51, #107)

examples/custom-menu/app.js
The `onSelect` logic was setting `state.unitedStates` to an empty array
which gave the impression that there were no matching results when the menu
was reopened.
=> Correctly filter items when selecting a state, fixes #81

lib/__tests__/.setup.js, lib/__tests__/Autocomplete-test.js, package.json
Replace custom jsdom + mocha + chai setup with jest. Also use jest's coverage reporter instead of isparta. The only real gain with this change is to prevent having to maintain our custom setup, and instead delegate to jest.
=> Replace mocha/chai/isparta with jest

lib/Autocomplete.js, lib/__tests__/Autocomplete-test.js
I believe this will resolve most of the funkyness we've been seeing when updating `items` on the fly while the user types, e.g. #52. /cc @sprjr
=> [fixed] Reset `highlightedIndex` when it's outside of `items.length`

lib/Autocomplete.js
I initially started by trying to fix a regression to #80 which was introduced
in 2fbafa, but after having evaluated the code I discovered that there's no
easy way to both fix the regression and make the typeahead logic work again.
This is sadly a side-effect of no longer keeping `value` in state, since we
can no longer diff previous state and next state in the same fashion.
Since the current typeahead situation is very poor on mobile, not to mention
how broken it is in IE, I decided the best way forward is to temporarily remove
the typeahead logic.
=> [removed] Remove typeahead (fixes #40, #111)

examples/index.html, examples/managed-menu-visibility/app.css, examples/managed-menu-visibility/app.js, examples/managed-menu-visibility/index.html, lib/Autocomplete.js, lib/__tests__/Autocomplete-test.js
This proposal adds two new props, `onMenuVisibilityChange: func` and `open: bool`. The former is invoked every time `state.isOpen` changes, and receives said value as its only argument. The latter - when present - overrides `state.isOpen` by putting the component into "managed menu visibility mode" (which is just a fancy way of saying `props.open` takes precedence over `state.isOpen`).
I created a new example (examples/managed-menu-visibility) to demonstrate the flexibility these additions offer.
This covers the request made in #129.
I personally need this feature to be able to use Autocomplete in a situation where I want to force the user to pick an option from the menu. Having the menu close when the input is blurred is needless to say not ideal ;)
@sprjr I'd like your input before …
=> Proposal: Managed menu visibility

lib/Autocomplete.js, lib/__tests__/Autocomplete-test.js
This change allows passing any prop to the `<input>` element via `props.inputProps`, apart from the ones we currently don't want the consumer to change (`role`, `aria-autocomplete`, and `autoComplete`).
The actual change in this PR is to ensure any event handlers we apply are added in addition to whatever the consumer specifies, instead of overwriting them.
=> [fixed] Prevent event handler clobbering (fixes #123)

README.md
The URL in the readme is still using the old domain name.
=> Update example URL

package.json
index.js simply does `module.exports = require('./Autocomplete')`, which is pointless. The package should instead point directly to Autocomplete.js.
=> Update package.json main to point to actual main file

lib/utils.js
The sorting in the example makes an effort to be clever, by sorting based on the location of the match. This is a great idea, but for the best user experience it should be complemented by alphabetical sorting when the match is in the same location (or there is no match).
For example, with the current version, searching for "e" shows the results in a confusing order:
After my change, all the states with "e" as their second letter are sorted alphabetically, then they're followed by other states with "e" elsewhere:
Similarly, with the empty state, the current sorting method is pretty hectic:
After my change, it's nice and alphabetical:
I also added a comment explaining what's going on, so people looking through the code understand why it's written this way 😛
=> Nicer sorting algorithm for example

README-template.md, README.md, bin/generate-api-doc.js, bin/generate-readme.js, lib/Autocomplete.js, package.json
This change introduces a generated `README.md` which is built using `README-template.md` and scripts from `bin/`. At the moment the scripts only generate the API documentation and dumps it into the `$API_DOC` placeholder found in the template. The documentation is generated by using `react-docgen` to extract comments from the source code.
The README is generated by running `npm run generate-readme`. This can either be done in the PR which introduces a change, or just before publishing (as described in "Publishing / Releasing").
@sprjr: Mind giving it a once-over before I merge this?
=> API documentation

lib/Autocomplete.js
The default value [causes an unnecessary iteration and array duplication](https://github.com/reactjs/react-autocomplete/blob/master/lib/Autocomplete.js#L209-L213) of
`items`. Since the default behaviour is to render all entries in `items` the
sensible thing to do is to skip this code path entirely and just use `items`
as is.
=> Remove shouldItemRender default value

lib/Autocomplete.js
I believe `wrapperStyle` is a shorthand for `wrapperProps` and not `inputProps`, but correct me if I'm mistaken.
=> Fix wrapperProps typo in README and comment

lib/Autocomplete.js
https://github.com/reactjs/react-autocomplete/issues/176 
> Uncaught TypeError: Cannot read property 'ownerDocument' of null #176
> This error occurs when user selects an item from the menu and then continues typing.
Seems itemNode is undefined in that case, this fixes that. 
Let's also fix https://github.com/reactjs/react-autocomplete/pull/173 so we get rid of those string refs
=> fix #176 - ownerDocument error ..for now
